server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?characterEncoding=utf8
    username: storeAdmin
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

